snippet classbuild123d "Add custom build123d object" b
class ${1:ClassName}(${2:BaseSketchObject|BasePartObject}):
	def __init__(
		self,
		${3: params},
		rotation: `!p
if t[2] == "BaseSketchObject":
	snip.rv = "float = 0"
elif t[2] == "BasePartObject":
	snip.rv = "RotationLike = (0, 0, 0)"
else:
	snip.rv = "= 0"
		`,
		align: `!p
if t[2] == "BaseSketchObject":
	snip.rv = "tuple[Align, Align] = (Align.CENTER, Align.CENTER)"
elif t[2] == "BasePartObject":
	snip.rv = "tuple[Align, Align, Align] = (Align.CENTER, Align.CENTER, Align.CENTER)"
else:
	snip.rv = "tuple[] = ()"
		`,
		mode: Mode = Mode.ADD,
	):
		with `!p
if t[2] == "BaseSketchObject":
	snip.rv = "BuildSketch"
elif t[2] == "BasePartObject":
	snip.rv = "BuildPart"
else:
	snip.rv = "BuildPart"`() as `!p snip.rv = t[1].lower()`:
		${0}

		`!p
if t[2] == "BaseSketchObject":
	snip.rv = f"super().__init__(obj={t[1].lower()}.sketch, rotation=rotation, align=align, mode=mode)"
elif t[2] == "BasePartObject":
	snip.rv = f"super().__init__(part={t[1].lower()}.part, rotation=rotation, align=align, mode=mode)"
else:
	snip.rv = "super().__init__()"
		`
endsnippet

snippet bd_p "Build part" b
with BuildPart() as ${1:part}:
	$0
endsnippet

snippet bd_s "Build sketch" b
with BuildSketch() as ${1:sketch}:
	$0
endsnippet

snippet bd_l "Build line" b
with BuildLine() as ${1:line}:
	$0
endsnippet
